# Generated by Django 6.0.3 on 2026-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mno',
            field=models.CharField(max_length=10),
        ),
    ]
